server.port=8081
spring.application.name=user_service
spring.data.mongodb.uri=mongodb://nguyenthuongaz9:nguyenthuong01@localhost:27017/hotelbooking?authSource=admin
eureka.client.service-url.defaultZone=http://localhost:8671/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
