spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=nguyenthuong01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083
spring.h2.console.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8671/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.webflux.client.timeout=5s



spring.cloud.loadbalancer.enabled=true


logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG